1password swarm_key syncing

diff --git a/scripts/swarm-keys b/scripts/swarm-keys
--- a/scripts/swarm-keys
+++ b/scripts/swarm-keys
@@ -1,30 +1,64 @@
 #!/bin/bash
+source .env
 
 CMD=$1
 KEY_NAME=swarm-keys
 
+# Sign into 1password if enabled
+op_logged_in=
+hasop=$(which op)
+if [ ! -z $hasop ] && [ ! -z $OP_VAULT_UUID ]; then
+  op_logged_in=$(op list vaults)
+  if [ -z $op_logged_in ]; then
+    eval $(op signin)
+
+    if [ -z $(op list vaults) ]; then
+      echo "Failed to sign in."
+      exit 1
+    fi
+  else
+    echo "Already signed into 1password."
+  fi
+fi
+
 if [[ $CMD == "sync" ]]; then
   echo; echo "Downloading swarm_keys from cluster..."
 
+  # Loop through all the validators
   validator_count=$(kubectl get pods | grep -c "validator")
   for ((i = 0 ; i < $validator_count ; i++)); do
     pod="validator-$i"
     echo; echo "Pod: $pod"
 
     miner_name=$(kubectl exec -it $pod -c validator -- sh -c "miner info name" | egrep -o "[a-z]+-[a-z]+-[a-z]+" | xargs)
-    address=$(kubectl exec -it $pod -c validator -- sh -c "miner peer addr")
-    address=$(echo $address | sed 's/\/p2p\///')
-
     echo "Miner Name: $miner_name"
-    echo "Miner Address: $address"
 
     mkdir -p keys
     mkdir -p keys/$miner_name
 
-    kubectl cp $pod:/var/data/miner/swarm_key keys/$miner_name/swarm_key -c validator
+    # Download the swarm_key
+    swarm_key_path=keys/$miner_name/swarm_key
 
-    echo "Make sure you backup keys/$miner_name/swarm_key in 1password or place of choice."
+    kubectl cp $pod:/var/data/miner/swarm_key $swarm_key_path -c validator > /dev/null
+    echo "Downloaded swarm_key to $swarm_key_path"
+
+    # Save to 1password
+    if [ ! -z $op_logged_in ]; then 
+      swarm_key_base64=$(echo "$(tr -d '\0' < $swarm_key_path)" | base64)
+      validator_login_title="$miner_name swarm_key"
+
+      uuid=$(op list items | jq -r --arg title "$validator_login_title" '[.[] | select(.overview.title | contains($title))][0] | .uuid')
+      if [ -z $uuid ] || [[ $uuid == "null" ]]; then
+        echo "No swarm_key found in 1password. Creating one..."
+        op create item login --vault "$OP_VAULT_UUID" title="$validator_login_title" password="$swarm_key_base64" notes="Automatically generated by helium-validator-k8s"
+      else
+        echo "swarm_key already saved in 1password"
+      fi
+    else
+      echo; echo "Make sure you backup keys/$miner_name/swarm_key in 1password or place of choice."
+    fi
   done
+
 
 elif [[ $CMD == "swap" ]]; then
   replica_id=$2
